### ISSUE TITLE
overlapping legend on sm.pl.heatmap when constrained_layout set to True, and default arguments

### ISSUE THREAD

**Issue by emmanuel-contreras** [labsyspharm/scimap#108]
A couple potential issues here with sm.pl.heatmap
 1) _constrained_layout_ set to True causes the legend to overlap the heatmap (see images below), setting it to False fixes this issue but I don't think it can be done as an argument to the heatmap function.
https://github.com/labsyspharm/scimap/blob/3e68c793ebe50bb28c087d45618b28bca2b4f92d/scimap/plotting/heatmap.py#L273

2)  ``` ValueError: Both 'saveDir' and 'fileName' must be provided together or not at all.```. **fileName** argument has a default value of 'heatmap.pdf', given the error, it may make more sense to set it to _None_ by default.

https://github.com/labsyspharm/scimap/blob/3e68c793ebe50bb28c087d45618b28bca2b4f92d/scimap/plotting/heatmap.py#L49

![image](https://github.com/labsyspharm/scimap/assets/14666496/6f620fbc-7478-48de-ac19-976d0292489c)

![image](https://github.com/labsyspharm/scimap/assets/14666496/ef5f6ea3-3cb4-4e12-81a2-32b4877ae697)

**Comment by ajitjohnson** [comment]
Thank you for reporting the bug @emmanuel-contreras. Why do think passing `constrained_layout` as a parameter would not work?

**Comment by emmanuel-contreras** [comment]
ohh, what I meant is that some refactoring will have to be done since ```constrained_layout``` is hard coded to True at the moment. But please correct me if I'm wrong.

**Comment by emmanuel-contreras** [comment]
Got it, yea that makes sense. I've been looking a bit more into this and it looks like the overlap is coming from the fixed positioning of the colorbar in these lines.

https://github.com/labsyspharm/scimap/blob/296885b512120aef3a622605159d741ad9ff03a8/scimap/plotting/heatmap.py#L303-L304

Looking at the colorbar positioning documentation I repositioned it with _inset_axes_, and it seems to work while leaving `constrained_layout`  set to True if you wanted to try it. Otherwise exposing `constrained_layout` would also work for now.
https://matplotlib.org/stable/users/explain/axes/colorbar_placement.html#using-inset-axes
```
cbar_ax = ax.inset_axes([-.5, -1.5, 4, .5], transform=ax.transData)
cbar = fig.colorbar(c, cax=cbar_ax, orientation='horizontal')
```

**Comment by ajitjohnson** [comment]
I am sorry I missed this. would you like to do a PR? I will accept and publish it. Sorry for the delay.

**Comment by ajitjohnson** [comment]
I published a new version recently so please pull the latest version to make changes, thank you.

**Comment by ajitjohnson** [comment]
hi @emmanuel-contreras sorry for the delay. I did not notice your message. I have released a new version with your changes.

**Comment by emmanuel-contreras** [comment]
No worries, thanks for merging the changes and for developing a great package!
