### ISSUE TITLE
Implicit change in matplotlib parameters while importing scimap

### ISSUE THREAD

**Issue by ConstensouxAlexis** [labsyspharm/scimap#111]
Hello,
I use SCIMAP package with Xenium spatial transcriptomics data. 
Before importing SCIMAP, I have no issues with plotting the Xenium data:
![before_scimap](https://github.com/user-attachments/assets/73c0e2ec-34a3-444d-aa56-11d0ce5d6e57)

But, when I import SCIMAP package and do the same plot, plotting parameters are changed so I cannot properly vizualise the Xenium data:
![after_scimap](https://github.com/user-attachments/assets/af412839-407e-4dc3-8343-918cb775db30)

It also raises the error message: 
findfont: Generic family 'sans serif' not found because none of the following families were found: Arial

So I guess SCIMAP changes matplotlib parameters but don't know where in the code, and why. Do you know if it is possible to bypass this behaviour ? Thanks !
I run scimap 2.1.1

**Comment by ajitjohnson** [comment]
hi @ConstensouxAlexis Thank you for raising the bug. Could you update the package `pip install scimap --upgrade` and check if the issue persists? Thank you.

**Comment by ConstensouxAlexis** [comment]
Hi @ajitjohnson , I saw that you changed matplotlib default params, so this should fix my issue. I just have an incompatibility with the new scimap version:
`scimap 2.1.2 requires dask[array]<2024.0.0,>=2023.11.0, but you have dask 2024.4.1 which is incompatible.`
`spatialdata 0.2.2 requires dask>=2024.4.1, but you have dask 2023.12.1 which is incompatible.`

I work on spatial transcriptomics data, so spatialdata library is necessary. I know scimap is not designed to work on spatial transcriptomics, but it provides a lot of useful features for spatial transcriptomics data analysis. It could be nice if scimap could support a more recent version of dask !
Thanks a lot

**Comment by ajitjohnson** [comment]
No problem. I have released a new version with the requirements relaxed. Hope it helps.
