### ISSUE TITLE
ValueError expecting 2D array at `sm.pp.rescale()` step

### ISSUE THREAD

**Issue by sobjb7osx2** [labsyspharm/scimap#120]
Hi team,

Thanks for a great package.
I'm getting this error at `sm.pp.rescale()` step:

ValueError: Expected 2D array, got 1D array instead: array=[5.18821837 5.42281853 5.92082633 ... 6.02203106 6.18514163 5.98150466]

This code : `data_gm = data[marker].values.reshape(-1, 1)` in gmm_gating function should result in 2D array that feeds into `GaussianMixture()` but maybe not? Could you please advise on what is going on?

I'm getting this error with and without manual gate specified. Thanks!

### 

Edit : Upon further inspection, it seems like any attempt to gate via GMM will result in this error. Unless gating information for all markers is provided, scimap throws this error.

**Comment by sobjb7osx2** [comment]
Upon further inspection, it seems like any attempt to gate via GMM will result in this error. Unless gating information for all markers is provided, scimap throws this error.

**Comment by rach-crc** [comment]
Hi, I hope this message finds you well. I wonder if you have found the solution to this, as I have encountered the same error after manual gating.

**Comment by ajitjohnson** [comment]
we have not been using GMM at all as they are not reliable. I was going remove it from the function. Is there a reason why that is useful?

**Comment by ajitjohnson** [comment]
this bug is now fixed!
