### ISSUE TITLE
ValueError: Expected 2D array, got 1D array instead for rescale after manual gating

### ISSUE THREAD

**Issue by rach-crc** [labsyspharm/scimap#124]
Dear Scimap Developers,

I hope this message finds you well. My group encountered one problem after running sm.pl.napariGater(image_path, adata, point_size=10) to gate each channel and manual_gate = pd.read_csv('manual_gates.csv') to import my gates (see attached figure), the following line: adata = sm.pp.rescale (adata, gate=manual_gate) did not work and reported an error (see the very end of this message), could you please kindly help us check what is going on?

We used SCIMAP  2.2.6, and we are using data of one single MIBI fov to test the package, cell table was generated from mesmer/deepcell, and converted to .h5ad version via anndata (full process see attached .md script).

<img width="537" alt="Screenshot 2024-12-09 at 19 48 16" src="https://github.com/user-attachments/assets/f24da648-8d57-4674-9bbd-d36a306c1c4a">

[Pipeline_outline.md](https://github.com/user-attachments/files/18067301/Pipeline_outline.md)

**_Error_**:
GMM for ['xxx']
Categories (1, object): ['xxx']

/opt/anaconda3/envs/scimap/lib/python3.10/site-packages/scimap/preprocessing/rescale.py:100: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[26], line 1
----> 1 adata = sm.pp.rescale (adata, gate=manual_gate)

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/scimap/preprocessing/rescale.py:245, in rescale(adata, gate, log, imageid, failed_markers, method, verbose, random_state)
    241 # run function
    242 r_gmm_gating_internal = lambda x: gmm_gating_internal (adata_subset=x, 
    243                                                        gate_mapping=gate_mapping,
    244                                                        method=method) 
--> 245 all_gates = list(map(r_gmm_gating_internal, adata_list))
    247 # combine the results and merge with gate_mapping
    248 result = []

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/scimap/preprocessing/rescale.py:242, in rescale.<locals>.<lambda>(x)
    240     adata_list = [adata[adata.obs[imageid] == i] for i in gmm_images]
    241 # run function
--> 242 r_gmm_gating_internal = lambda x: gmm_gating_internal (adata_subset=x, 
    243                                                        gate_mapping=gate_mapping,
    244                                                        method=method) 
    245 all_gates = list(map(r_gmm_gating_internal, adata_list))
    247 # combine the results and merge with gate_mapping

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/scimap/preprocessing/rescale.py:220, in rescale.<locals>.gmm_gating_internal(adata_subset, gate_mapping, method)
    218 # identify the gates for the markers
    219 r_gmm_gating = lambda x: gmm_gating(marker=x, data=data_subset_clipped) 
--> 220 gates = list(map(r_gmm_gating, marker_to_gate))     
    221 # create a df with results
    222 result = image_specific[image_specific.gate.isnull()]

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/scimap/preprocessing/rescale.py:219, in rescale.<locals>.gmm_gating_internal.<locals>.<lambda>(x)
    217     data_subset_clipped = np.log1p(data_subset_clipped)
    218 # identify the gates for the markers
--> 219 r_gmm_gating = lambda x: gmm_gating(marker=x, data=data_subset_clipped) 
    220 gates = list(map(r_gmm_gating, marker_to_gate))     
    221 # create a df with results

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/scimap/preprocessing/rescale.py:189, in rescale.<locals>.gmm_gating(marker, data)
    186 data_gm = data_gm[~np.isnan(data_gm)]
    188 # Fit GMM with 3 components
--> 189 gmm = GaussianMixture(n_components=3, random_state=random_state).fit(data_gm)
    191 # Sort components by their means
    192 means = gmm.means_.flatten()

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/sklearn/mixture/_base.py:181, in BaseMixture.fit(self, X, y)
    155 """Estimate model parameters with the EM algorithm.
    156 
    157 The method fits the model ``n_init`` times and sets the parameters with
   (...)
    178     The fitted mixture.
    179 """
    180 # parameters are validated in fit_predict
--> 181 self.fit_predict(X, y)
    182 return self

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/sklearn/base.py:1473, in _fit_context.<locals>.decorator.<locals>.wrapper(estimator, *args, **kwargs)
   1466     estimator._validate_params()
   1468 with config_context(
   1469     skip_parameter_validation=(
   1470         prefer_skip_nested_validation or global_skip_validation
   1471     )
   1472 ):
-> 1473     return fit_method(estimator, *args, **kwargs)

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/sklearn/mixture/_base.py:212, in BaseMixture.fit_predict(self, X, y)
    184 @_fit_context(prefer_skip_nested_validation=True)
    185 def fit_predict(self, X, y=None):
    186     """Estimate model parameters using X and predict the labels for X.
    187 
    188     The method fits the model n_init times and sets the parameters with
   (...)
    210         Component labels.
    211     """
--> 212     X = self._validate_data(X, dtype=[np.float64, np.float32], ensure_min_samples=2)
    213     if X.shape[0] < self.n_components:
    214         raise ValueError(
    215             "Expected n_samples >= n_components "
    216             f"but got n_components = {self.n_components}, "
    217             f"n_samples = {X.shape[0]}"
    218         )

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/sklearn/base.py:633, in BaseEstimator._validate_data(self, X, y, reset, validate_separately, cast_to_ndarray, **check_params)
    631         out = X, y
    632 elif not no_val_X and no_val_y:
--> 633     out = check_array(X, input_name="X", **check_params)
    634 elif no_val_X and not no_val_y:
    635     out = _check_y(y, **check_params)

File /opt/anaconda3/envs/scimap/lib/python3.10/site-packages/sklearn/utils/validation.py:1050, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_writeable, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
   1043         else:
   1044             msg = (
   1045                 f"Expected 2D array, got 1D array instead:\narray={array}.\n"
   1046                 "Reshape your data either using array.reshape(-1, 1) if "
   1047                 "your data has a single feature or array.reshape(1, -1) "
   1048                 "if it contains a single sample."
   1049             )
-> 1050         raise ValueError(msg)
   1052 if dtype_numeric and hasattr(array.dtype, "kind") and array.dtype.kind in "USV":
   1053     raise ValueError(
   1054         "dtype='numeric' is not compatible with arrays of bytes/strings."
   1055         "Convert your data to numeric values explicitly instead."
   1056     )

ValueError: Expected 2D array, got 1D array instead:
array=[0.         0.         0.         ... 0.         0.00604231 0.        ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by ajitjohnson** [comment]
can you send me your anndata object and manual_gates.csv? I can quickly check.

**Comment by rach-crc** [comment]
> Can you send me your anndata object and manual_gates.csv? I can quickly check.
> 
> I need to check the raw data vs what is within `adata.X`. You manual gates seems to be very small- are these log normalized ?

Yes, willing to do so. But the adata was to big to directly insert in email, so I compressed it to zip file. Here is the anndata of this single fov and the manual_gates for it. 
[ark_1.h5ad.zip](https://github.com/user-attachments/files/18068742/ark_1.h5ad.zip)
[manual_gates.csv](https://github.com/user-attachments/files/18068746/manual_gates.csv)

I have also noticed my gates for markers are quite low (e.g., many around 0.0xxxx) is it due to the nature of MIBI images, that they are not flurescence are they are naturally dim. Will this affect the sensitivity of the algorithm of Scimap?

**Comment by ajitjohnson** [comment]
The `manual_gate` markers and the marker names in your `adata` object do not match, which is why you encountered the error. To resolve this issue, you can use the following code:

```python
adata.var.index = manual_gate['marker']
```

This should fix the error for now.

Additionally, I noticed the following snippet in your script:

```python
adata = ad.AnnData(exp_data)
adata.raw = ad.AnnData(raw_exp_data)
```

It's unclear how `exp_data` differs from `raw_exp_data`. However, I would like to point out that `scimap` defaults to using the raw data and applies a log transformation when using the `napariGater` function. Given that your raw data already has a narrow range, I recommend avoiding the log transformation and directly using the raw data during gating. For example:

```python
sm.pl.napariGater(image_path, adata, layer='raw', log=False)
```

When rescaling, you can again ensure the log transformation is disabled by setting `log=False`:

```python
adata = sm.pp.rescale(adata, gate=manual_gate, log=False)
```

**Comment by rach-crc** [comment]
> The `manual_gate` markers and the marker names in your `adata` object do not match, which is why you encountered the error. To resolve this issue, you can use the following code:
> 
> ```python
> adata.var.index = manual_gate['marker']
> ```
> 
> This should fix the error for now.
> 
> Additionally, I noticed the following snippet in your script:
> 
> ```python
> adata = ad.AnnData(exp_data)
> adata.raw = ad.AnnData(raw_exp_data)
> ```
> 
> It's unclear how `exp_data` differs from `raw_exp_data`. However, I would like to point out that `scimap` defaults to using the raw data and applies a log transformation when using the `napariGater` function. Given that your raw data already has a narrow range, I recommend avoiding the log transformation and directly using the raw data during gating. For example:
> 
> ```python
> sm.pl.napariGater(image_path, adata, layer='raw', log=False)
> ```
> 
> When rescaling, you can again ensure the log transformation is disabled by setting `log=False`:
> 
> ```python
> adata = sm.pp.rescale(adata, gate=manual_gate, log=False)
> ```

Thank you so much for your help and advice. Have a great week.
