### ISSUE TITLE
sm.pl.foldchange runs into KeyError

### ISSUE THREAD

**Issue by josenimo** [labsyspharm/scimap#14]
Dear scimap developer,

I am Jose, a biologist who now requires to perform multiplex image analysis. I have ran MCMICRO, and load the output csv as AnnData object. While trying to visualize the data, the foldchange function runs into an error, I am probably doing something wrong. 
[foldchange_KeyError.txt](https://github.com/labsyspharm/scimap/files/7925716/foldchange_KeyError.txt)
[conda list.txt](https://github.com/labsyspharm/scimap/files/7925720/conda.list.txt)

**Comment by ajitjohnson** [comment]
Hi @josenimo Thank you for reporting your issue. Could you please paste the commands that you ran before you got this error? Thank you. 

I see that you ran `sm.pl.foldchange`, Did you run `sm.tl.foldchange`, prior to running the plotting function? Thank you.

**Comment by josenimo** [comment]
Hey Ajit, 
I am quite silly, I did not run the sm.tl.foldchange. I was even watching your tutorial as you did the simimlar steps for the PCA, just did not catch the detail. Thank you for developping such a neat tool! I will be trying the Cell Phenotyping tutorial later this week. 
Best, Jose

**Comment by ajitjohnson** [comment]
No problem. Glad you were able to solve it :)
