### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by sailseem** [labsyspharm/scimap#17]
Dear developer,

I am just wondering that is there any way to install scimap on a M1 chip MacBook? I got errors in pip install scimap

Thanks in adcance

**Comment by ajitjohnson** [comment]
Hi @sailseem can you paste the error here? I am not sure if `Napari` installation has been fixed for M1 yet, if not that is likely the one feature (i.e, to view images) you may not be able to use, other than that everything should work. 

I highly recommend installing within a conda environment

```
conda create --name scimap python=3.8
# once the environment is installed
pip install scimap
```

**Comment by sailseem** [comment]
sorry, it was my bad, scimap works well under python=3.8. I got an version issue before, sorry for this, I will close this. Thanks for your help.
