### ISSUE TITLE
sm.pl.gate_finder

### ISSUE THREAD

**Issue by sailseem** [labsyspharm/scimap#18]
Dear developer,

When I run sm.pl.gate_finder function, the window did not pop up? And everything looks good. Any ideas? Thanks a lot.
![image](https://user-images.githubusercontent.com/72428172/161116632-840c0975-bfb2-4b96-a0c9-b84c573fcd92.png)

**Comment by ajitjohnson** [comment]
Ah yes, that is because as I mentioned earlier, `Napari` does not work on M1. I am not sure if has been fixed yet. There might be some solutions that might work: https://forum.image.sc/t/issue-with-downloading-napari-on-mac-m1-chip/53961/12

If you can get Napari working, that function will work.

**Comment by boyuan-zhang** [comment]
Napari installation requires python 3.9, so, i cannot install scimap under py3.9.  The errors like this,
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, joblib, igraph, h5py, fonttools, fasteners, dask, cycler, zarr, scikit-learn, pytest, plotly, numexpr, numba, matplotlib, Markdown, leidenalg, ghp-import, gensim, tables, statsmodels, sklearn, seaborn, pytest-xvfb, pynndescent, pymdown-extensions, PhenoGraph, mkdocs, anndata, umap-learn, mkdocs-material, scanpy, scimap
  Running setup.py install for llvmlite ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running install
      /Users/boyuan/opt/anaconda3/envs/napari/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      got version from file /private/var/folders/9b/qygw7j553_1bdzx6bgb86b5w0000gn/T/pip-install-vsjdthow/llvmlite_fbaa91c718ee4c7b880003d8e60ecdc9/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
      running build_ext
      /Users/boyuan/opt/anaconda3/envs/napari/bin/python3.9 /private/var/folders/9b/qygw7j553_1bdzx6bgb86b5w0000gn/T/pip-install-vsjdthow/llvmlite_fbaa91c718ee4c7b880003d8e60ecdc9/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/private/var/folders/9b/qygw7j553_1bdzx6bgb86b5w0000gn/T/pip-install-vsjdthow/llvmlite_fbaa91c718ee4c7b880003d8e60ecdc9/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/Users/boyuan/opt/anaconda3/envs/napari/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/Users/boyuan/opt/anaconda3/envs/napari/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/Users/boyuan/opt/anaconda3/envs/napari/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Users/boyuan/opt/anaconda3/envs/napari/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/9b/qygw7j553_1bdzx6bgb86b5w0000gn/T/pip-install-vsjdthow/llvmlite_fbaa91c718ee4c7b880003d8e60ecdc9/ffi/build.py", line 191, in <module>
          main()
        File "/private/var/folders/9b/qygw7j553_1bdzx6bgb86b5w0000gn/T/pip-install-vsjdthow/llvmlite_fbaa91c718ee4c7b880003d8e60ecdc9/ffi/build.py", line 185, in main
          main_posix('osx', '.dylib')
        File "/private/var/folders/9b/qygw7j553_1bdzx6bgb86b5w0000gn/T/pip-install-vsjdthow/llvmlite_fbaa91c718ee4c7b880003d8e60ecdc9/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/Users/boyuan/opt/anaconda3/envs/napari/bin/python3.9' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.




Well, when I installed scimap under python3.8, the napari did not show up when run the gate_finder. I don't know why, can you help me with it? Thanks

**Comment by ajitjohnson** [comment]
Hello @sailseem @boyuan-zhang 

After 3 sleepless nights and updating 50+ dependencies, I finally have a solution to install `scimap` on M1 machines. 

Please note, there are multiple major packages that do not yet support to `M1 machines` and so this is a temporary solution until everyone updates their packages to support M1. 

Please follow the instructions in the given order. Napari works as well! Hope it helps.

```
# create and load a new environment
conda create -y -n scimap -c andfoy python=3.9 pyqt
conda activate scimap

# if you do not have xcode please install it
xcode-select --install

# if you do not have homebrew please install it
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# if you do not have cmake install it
brew install cmake

# install h5py
brew install hdf5@1.12
export HDF5_DIR=/opt/homebrew/Cellar/hdf5/1.12.1_1/
pip install --no-binary=h5py h5py

# install llvmlite
conda install llvmlite -y

# install leidenalg
pip install git+https://github.com/vtraag/leidenalg.git

# install scimap
pip install -U scimap

# uninstall 
conda remove llvmlite -y
pip uninstall numba -y
pip uninstall numpy -y

# reinstall this specific version of llvmlite (ignore errors/warning)
pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple llvmlite

# reinstall this specific version of numpy (ignore errors/warning)
pip install numpy==1.22.3

# reinstall this specific version of numba (ignore errors/warning)
pip install -i https://pypi.anaconda.org/numba/label/wheels_experimental_m1/simple numba
```

**Comment by sailseem** [comment]
Thank you very much, man. I do appreciate your help and feel sorry to cause this huge trouble. 
Thanks, again! Hey, take a good sleep.

**Comment by ajitjohnson** [comment]
haha, no probs. It was long overdue. Let me know if it works :)
