### ISSUE TITLE
spatial_LDA with KNN neighborhoods

### ISSUE THREAD

**Issue by yerahko** [labsyspharm/scimap#27]
Hi there,

I am running into trouble when I try to run the function spatial_LDA using method='knn', i.e.:
https://github.com/labsyspharm/scimap/blob/b957d8d771260947c4f783b62533c0d0c3c48e5a/scimap/tools/_spatial_lda.py#L96-L112

I am getting the following error at line 112:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

      [1] for i in range(len(ind)):
----> [2]     ind[i] = [phenomap[letter] for letter in ind[i]]

ValueError: invalid literal for int() with base 10: 'B'
```

Using method='radius' works. 

Thank you very much for your help!

**Comment by ajitjohnson** [comment]
Hi @yerahko Thank you for reporting this bug. I fixed it. Can you please update the package `pip install scimap --upgrade` and try again? Thank you.

**Comment by yerahko** [comment]
Hi @ajitjohnson, it works now. Thank you for looking into that so quickly!
