### ISSUE TITLE
image_viewer and gate_finder do not work: type object 'SubControl' has no attribute 'SC_None'

### ISSUE THREAD

**Issue by SarkkinenJ** [labsyspharm/scimap#30]
Hi,

and thank you for developing scimap! Unfortunately though, I have had problems with sm.pl.image_viewer and sm.pl.gate_finder, where I keep getting the same error: 
`type object 'SubControl' has no attribute 'SC_None'`
All the previous steps in scimap tutorials have worked smoothly. Apparently the problem is in opening Napari. Two collaborators have kindly tried to use image_viewer and gate_finder using the same data and they have not had any problems. However, I am the only one using Mac (currently Monterey 12.4), so could this be a Mac-Napari thing? 

Here is a [link](https://datacloud.helsinki.fi/index.php/s/tJPLyzmorQp8AM2) to a jupyter notebook example, error message and to example image. 

Any help will be much appreciated. 

Best, 
Joona

**Comment by ajitjohnson** [comment]
Hi Joona,

Glad you are trying out `scimap`

I tried your data and it works on my computer which is `Monterey 12.4` as well.

Can you let me know if you are installing `scimap` within a conda environment?

I would do the following steps

```
conda create --name scimap -y python=3.9
conda activate scimap
pip install scimap 
```
