### ISSUE TITLE
sm.pl.image_viewer works but the Napiri visualization wont pop up

### ISSUE THREAD

**Issue by bugie19** [labsyspharm/scimap#34]
Halloo everyone........

I am a new for the bioinformatic analysis. Currently, I am working on spatial CODEX imaging analysis and I found this package very useful. However I have encounter a problem in using sm.pl.image_viewer. It seems the code is working but Napiri visualization wont pop up. this is my code I put on:

>>>import sys
>>>import os
>>>import anndata as ad
>>>import pandas as pd
>>>import scanpy as sc
>>>import seaborn as sns; sns.set(color_codes=True)
>>># Import Scimap
>>>import scimap as sm
>>> # Set the working directory
>>> os.chdir ("/Users/admin/Desktop/scimap package.CODEX.analysis/")
>>> # Load data
>>> adata = ad.read('tutorial_data_D20LN1_setting5.h5ad')
>>> adata
AnnData object with n_obs × n_vars = 8957 × 24
    obs: 'X_centroid', 'Y_centroid', 'Area', 'MajorAxisLength', 'MinorAxisLength', 'Eccentricity', 'Solidity', 'Extent', 'Orientation', 'CellID', 
   'imageid'
    uns: 'all_markers', 'pca'
    obsm: 'X_pca'
    varm: 'PCs'
>>> image_path = '/Users/admin/Desktop/scimap package.CODEX.analysis/image.ome.tif'
>>> sm.pl.image_viewer(image_path, adata, overlay='leiden',overlay_category=None,
...                 markers=[ 'CD8'], imageid='imageid', seg_mask=None,                
...                 point_size=7,point_color='white')
>>>

the data put for adata was h5ad. 

Any help I really appreciate. 

Best regards,

Bugie

**Comment by ajitjohnson** [comment]
Hi @bugie19 Could you let me know what computer are you using? 
Can you also check if napari works natively? You can find out by simply typing `napari` in terminal within the conda environment that you use for `scimap`. 
The most common issue is that some of the dependencies for `napari` is not properly installed such as `pyqt5`

**Comment by bugie19** [comment]
Hi ajitjhonson,

as your suggestion, I reinstalled pyqt5 and the Napari visualization can be called. Thanks a lot. 

best regards,

Bugie
