### ISSUE TITLE
Wrong figure in the "Getting Started with Scimap" tutorial

### ISSUE THREAD

**Issue by ziyuanzhao2000** [labsyspharm/scimap#74]
For the "Getting Started with Scimap" tutorial found [here](https://scimap.xyz/tutorials/1-scimap-tutorial-getting-started/#tutorial-material), starting from the given files and python script, I obtain a PCA plot that looks like the following:

![image](https://github.com/labsyspharm/scimap/assets/78766247/ceead3ff-c8e6-4ecd-9b02-8718010a8ab6)

This agrees with the figure shown in the YouTube tutorial [here](https://www.youtube.com/watch?v=knh5elRksUk) but is different from the result displayed on that webpage version of the tutorial. So, there might be some issue with how that plot is generated that you may consider fixing. Thanks!

**Comment by ajitjohnson** [comment]
Thank you @ziyuanzhao2000 

I apologize for missing this issue. For some reason, I have not been receiving notifications for the issues raised in this channel.
