### ISSUE TITLE
%gui qt not running (M2)

### ISSUE THREAD

**Issue by virlyananda** [labsyspharm/scimap#82]
Hi,

I've been encountering an issue where I couldn't open Napari when I ran %gui qt. Currently, this has been happening whenever I run it on M2. It works just fine when I ran it on non M1/M2 OS. Any recommendation on how to fix this?
<img width="1051" alt="Screenshot 2023-11-07 at 3 43 19 PM" src="https://github.com/labsyspharm/scimap/assets/70969092/77ae423c-7ea0-4e12-8d21-8c47cec5e077">

Thanks,
Virly

**Comment by josenimo** [comment]
I run it on M2 just fine, I followed the standard installation instructions and then just had to install PyQt6 on the side with pip, inside the mamba environment. can you post your entire package list with ```conda list```

**Comment by ajitjohnson** [comment]
I should probably add `PyQt` as a requirement again. I had included it previously, but it caused some issues, so I removed it. However, I no longer remember what those issues were.
