### ISSUE TITLE
np.warnings.filterwarnings('ignore') no longer supported by numpy 

### ISSUE THREAD

**Issue by milesbailey121** [labsyspharm/scimap#92]
Hi, 
I've been having an issue when running sm.pl.gate_finder() it throws AttributeError: module 'numpy' has no attribute 'warnings' 
This carries from np.warnings.filterwarnings('ignore') on line 148 in gate_finder().

I think I found a fix, it seem to have replaced this with the np.seterr('ignore') function in the newer versions of numpy 

NumPy version = 1.26.4

Code Used: 
`sm.pl.gate_finder (image_path, adata, marker_of_interest,
                   from_gate = 5, to_gate = 9, increment = 0.1, 
                   point_size=10)`

**Comment by milesbailey121** [comment]
@ajitjohnson I've just checked with the latest version and it works perfectly. Thank you very much for resolving the issue!

**Comment by ajitjohnson** [comment]
thank you :)
