### ISSUE TITLE
upgrade the latest version

### ISSUE THREAD

**Issue by yas92** [labsyspharm/scimap#97]
HI 
May I ask how to upgrade to the latest version in jupyter notebook since I have 1.3.2 version and some of tools (functions) are not able to use.

**Comment by ajitjohnson** [comment]
Hi @yas92 this applies to any package - `pip install scimap --upgrade`. If you are executing this command in jupyter notebook add a`!` in front -- `!pip install scimap --upgrade`

**Comment by ajitjohnson** [comment]
have you run `sm.tl.spatial_pscore`? The one that you have says that you are running the plotting function. If you haven't already (most likely the case), you will need to run the tool variant of the function that does the actual calculations.
