### ISSUE TITLE
.vscode in the repo

### ISSUE THREAD

**Issue by kevinyamauchi** [labsyspharm/scimap#98]
Hello! Super minor point, but I noticed that a .vscode directory is included in the repo. It would be nice to remove as these  VSCode settings might collide with other people's settings. Thanks!

This comment is part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/6604

**Comment by ajitjohnson** [comment]
Thank you for bringing this to my attention. I have removed it and added it to the Git ignore list. I will push an updated version to pip once all the reviews have been addressed. Thank you.
